export interface Klassenleitung {
	id: number,
	vorname: string,
	nachname: string,
	name: string,
	geschlecht: string,
	klasse: string,
	bemerkung: object,
	fachbezogeneBemerkungen: string,
    ASV: string,
    AUE: string,
    ZB: string,
	asv: string,
	aue: string | null,
	zb: string | null,
	gfs: Number,
	gfsu: Number,
	editable: {
		fehlstunden: boolean,
		asv: boolean,
		aue: boolean,
		zb: boolean,
	},
}